Django_samp_project/star_social_demo/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
     path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
     path('logout/',auth_views.LogoutView.as_view(),name='logout'),
     path('signup/',views.SignUp.as_view(),name="signup"),
]

Django_samp_project/star_social_demo/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

Django_samp_project/star_social_demo/star_social_demo/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from  django.conf import settings

# modified admin
admin.site.site_header="STAR_SOCIAL"
admin.site.site_title="star social"
admin.site.index_title="star social demo"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name="home"),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name="test"),
    path('thanks/',views.ThanksPage.as_view(),name="thanks"),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Django_samp_project/star_social_demo/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Star Social Demo</title>
    <link rel="shortcut icon" href="{% static 'star_social_demo/images/icons8-rocket-100.ico'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
  
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'star_social_demo/css/master.css'%}">
                                
</head>
<body>
    <nav class="navbar navbar-dark bg-dark mb-xl-4" role="navigation" id='navbar'>
        <div class="container">
            <a class='navbar-brand mynav' href="{% url 'home' %}">
                <img class="rocket" src="{% static 'star_social_demo/images/icons8-rocket-100.png'%}" width="32px" height="32px"   alt="ロケット">
                Star Social
            </a>
            
            <ul class="nav justify-content-center navbar-right">

                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'posts:create' %}" class="nav-link"  class="btn btn-simpe">Post</a></li>
                    <li class="nav-item"><a href="{% url 'groups:all' %}" class="nav-link"  class="btn btn-simpe">Groups</a></li>
                    <li class="nav-item"><a href="{% url 'groups:create' %}" class="nav-link"  class="btn btn-simpe">Creat Groups</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link"  class="btn btn-simpe">Log Out</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'groups:all' %}" class="nav-link"  class="btn btn-simpe">Groups</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-item nav-link"  class="btn btn-simple">Login</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:signup' %}" class="nav-item nav-link"  class="btn btn-simple">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <canvas id="canvas"></canvas>
    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="{% static 'star_social_demo/js/master.js' %}" type="text/JavaScript"></script>
</body>
</html>

Django_samp_project/star_social_demo/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class='row'>
        <p></p>
    </div>
    <div class='row'>
        <p></p>
    </div>
    <div class="row">
        <div class="col-lg">
            <h1>Welcome to Star Social! </h1>
        </div>
    </div>
</div>
{% endblock %}

Django_samp_project/star_social_demo/templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are logged in! </h1>
  
{% endblock content %}

Django_samp_project/star_social_demo/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for Visiting,  back again! </h1>
  
{% endblock content %}