Django_samp_project/star_social_demo/groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    # path('<int>',views.ListGroups.as_view(),name='all'),
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('post/in/<slug>',views.SingleGroup.as_view(),name='single'),
    path('join/<slug>',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>',views.LeaveGroup.as_view(),name='leave'),
]

Django_samp_project/star_social_demo/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
]

Django_samp_project/star_social_demo/star_social_demo/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from  django.conf import settings

# modified admin
admin.site.site_header="STAR_SOCIAL"
admin.site.site_title="star social"
admin.site.index_title="star social demo"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name="home"),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name="test"),
    path('thanks/',views.ThanksPage.as_view(),name="thanks"),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Django_samp_project/star_social_demo/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
import misaka

from django.contrib.auth import get_user_model

User = get_user_model()

from django import template

register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=225,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,blank=True,default='')
    member = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name,True)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)
    
    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})
    
    class Meta:
        ordering = ['-id']
        

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)
    

    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('group','user')

Django_samp_project/star_social_demo/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin,PermissionRequiredMixin)
from django.shortcuts import get_object_or_404

# Create your views here.
from django.urls import reverse
from django.views import generic

from groups.models import Group,GroupMember
from . import models

# Exception raised when the relational integrity of the database is affected, 
# e.g. a foreign key check fails, duplicate key, etc.
from django.db import IntegrityError

from django.contrib import messages

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    # ,generic.list.MultipleObjectMixin
    model = Group
    # object_list = group.posts.all()
    # paginate_by = 5
    # def get_context_data():
    #     object_list = Group.objects.filter(name=self.object)


class ListGroups(generic.ListView):
    paginate_by = 5
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,('Warning already a member!'))
        else:
            messages.success(self.request,'Yout are now a member!')
    
        return super().get(request,*args,**kwargs)

        
class LeaveGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self,request,*args,**kwargs):

        try: 
            membership = models.GroupMember.objects.filter(
                user = self.request.user,
                group__slug = self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,"sorry you aren'/t in this group")

        else:
            membership.delete()
            messages.success(self.request,"you have left the group")
        return super().get(request,*args,**kwargs)    

Django_samp_project/star_social_demo/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>
  
{% endblock content %}

Django_samp_project/star_social_demo/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% load static %}
<div class="container">
{% block pregroup %}
<script src="{% static 'star_social_demo/js/group_detail.js' %}" type="text/JavaScript"></script>
            <div class='content'>
            <h1 class="mb-xl-4">{{group.name}}
                {% if user in group.member.all %}
                    <a href="{% url 'groups:leave' slug=group.slug %}" class='btn  btn-lg btn-fill btn-warning'>
                        <span class="glyphicon glypicon-remove-circle"></span>Leave
                    </a>
                {% else %}
                    <a href="{% url 'groups:join' slug=group.slug %}" class='btn  btn-lg btn-fill btn-warning'>
                        <span class="glyphicon glypicon-ok-circle"></span>Join
                    </a>
                {% endif %}
            </h1>
            <br />
            <h2><u>Member Count:</u> <span class="badge badge-success mb-xl-4">{{ group.member.count }}</span></h2>
        </div>
{% endblock pregroup %}


{% block group_content %}
    <div class="content">
        <div class="m-xl-5">
        {% if group.posts.count == 0 %}
            <h2>No posts in this group yet!</h2>     
        {% else %} 
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %}
        {% endfor %}   
        {% endif %}
        </div>
    </div>
{% endblock group_content %}
</div>








    

Django_samp_project/star_social_demo/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}


{% block group_content %}
<div class="container">
    <h4>Create a new group!</h4>
    <br />
    <form action="{% url 'groups:create' %}" method="post" id='groupForm'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-large" value="Create">
    </form>
</div>
{% endblock group_content %}

Django_samp_project/star_social_demo/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}


{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
              <h2 class="mb-xl-2"> Wellcome Back! </h2>
              <h2>
                  <span class="flash">
                    <a href="{% url 'posts:for_user' username=user.username %}">
                        @{{ user.username }}
                    </a>
                  </span>
              </h2>
            {% endif %}
            <h2 class="title mb-xl-5">Groups</h2>
            <p>Welcome to the groups page!</p>
            <p>Select a Group with a shared interest!</p>
        </div>
        <br /> 
        {% if user.is_authenticated  %}
          <a href="{% url 'groups:create' %}"  class="btn btn-warning">
              <span class="glyphicon glypicon-plus-sign">Create New Groups!</span>
          </a>
        {% endif %}
    </div>
{% endblock pregroup %}
    


{% block group_content %}
<div class="col-md-8">
    <div class="list-group mb-xl-3">
        {% for group in page_obj  %}
        <a class="list-group-item list-group-item-action" href="{% url 'groups:single' slug=group.slug %}">
            <h3 class="title list-group-item-heading"><strong>{{ group.name }}</strong></h3>
            <div class="list-group-item-text container-fluid">
                <u>{{ group.description_html|safe }}</u>
            </div>
          <div class="row">
              <div class="col-md-4">
                  <span class="badge badge-pill badge-info">{{ group.member.count }}</span>
                  member{{ group.member.count|pluralize }}
              </div>
              <div class="col-md-4">
                  <span class="badge badge-pill badge-info">{{ group.posts.count }}</span>
                  post{{ group.posts.count|pluralize }}
              </div>
          </div>
        </a>
        {% endfor %}
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">      
                <li class="page-item">
                    {% if page_obj.has_previous %}  
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        {% else %}
                    <a class="page-link" aria-label="Previous" aria-disabled="true">
                        {% endif %}
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span> 
                    </a>
                </li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                <li class="page-item">
                    {% if page_obj.has_next %}
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        {% else %}
                    <a class="page-link" aria-label="Next" aria-disabled="true">
                        {% endif %} 
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
        </ul>
    </nav>
    </div>

{% endblock group_content %}
    